version: "3"

services:
  # consumer-mongodb:
  #   build: ./consumer-mongodb
  #   entrypoint: /home/node/consumer-mongodb/.docker/entrypoint.sh
  #   container_name: consumer-mongodb
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   ports:
  #     - 3001:3333
  #   volumes:
  #     - ./consumer-mongodb:/home/node/consumer-mongodb
  #   # depends_on:
  #   #   - rabbitmq

  producer-oxygen:
    build: ./producer-oxygen
    entrypoint: /home/node/producer-oxygen/.docker/entrypoint.sh
    container_name: producer-oxygen
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./producer-oxygen:/home/node/producer-oxygen
    depends_on:
      - rabbitmq

  producer-humidity:
    build: ./producer-humidity
    entrypoint: /home/node/producer-humidity/.docker/entrypoint.sh
    container_name: producer-humidity
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./producer-humidity:/home/node/producer-humidity
    depends_on:
      - rabbitmq

  producer-temperature:
    build: ./producer-temperature
    entrypoint: /home/node/producer-temperature/.docker/entrypoint.sh
    container_name: producer-temperature
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./producer-temperature:/home/node/producer-temperature
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
